import {useState, useMemo} from 'react'
import Head from 'next/head'
import Image from 'next/image'



export async function getServerSideProps() {
  const res = await fetch(`
    https://imdb-api.com/en/API/Top250Movies/${process.env.IMDB_API_KEY}
  `);
  const data = await res.json();

  return {
    props: {
      movies: data.items,
    }
  }
}

export default function Home({movies}) {

  const [filter, setFilter] = useState('')

  const filteredMovies = useMemo(
    () =>
      movies.filter((movie) =>
        movie.title.toLowerCase().includes(filter.toLowerCase())
      ),
    [filter, movies]
  );


  return (
    <div className='app'>
      <Head>
        <title>Movieooze</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1>Movieooze</h1>
      {/* <div className="top-title">
        <h4>Top 250 Movies</h4>
      </div> */}
      <div className="search">
        <input
          type="text"
          value={filter}
          onChange={(e) => setFilter(e.target.value)}
          placeholder ='Search movies'
        />
      </div>

      {filteredMovies?.length > 0 ? (
         <div className="container">
         {filteredMovies.slice(0, 21).map((movie) => (
           <div key={movie.id} className='movie'>
            <div>
              <p>{movie.year}</p>
            </div>
            <div>
             
              <Image src={movie.image !== "N/A" ? movie.image : "https://via.placeholder.com/400"} alt={movie.title} height={400} width={320}/>
            </div>
            <div>
              <span>{movie.imDbRating}</span>
              <h3>{movie.fullTitle}</h3>
            </div>
           </div>
         ))}
       </div>
      ) : (
        <div className="empty">
          <h2>No movies found! Try searching again</h2>
        </div>
      )}

      <div className="footer">
        <p>Website by: jlargo</p>
      </div>
     
    </div>
  )
}
