import {useState, useMemo} from 'react'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'


export async function getServerSideProps() {
  const res = await fetch(`
    https://imdb-api.com/en/API/Top250Movies/${process.env.IMDB_API_KEY}
  `);
  const data = await res.json();

  return {
    props: {
      movies: data.items,
    }
  }
}

export default function Home({movies}) {

  const [filter, setFilter] = useState('')

  const filteredMovies = useMemo(
    () =>
      movies.filter((movie) =>
        movie.title.toLowerCase().includes(filter.toLowerCase())
      ),
    [filter, movies]
  );


  return (
    <div className={styles.main}>
      <Head>
        <title>Movieooze</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div>
        <input
          type="text"
          value={filter}
          onChange={(e) => setFilter(e.target.value)}
          className={styles.search}
        />
      </div>

      <div>
        <h1>Top 250 Movies</h1>
      </div>

      {filteredMovies?.length > 0 ? (
         <div className={styles.container}>
         {filteredMovies.slice(0, 20).map((movie) => (
           <div key={movie.id} className={styles.image}>
             <Image src={movie.image} height={400} width={400} alt={movie.title} />
             
             <h2>{movie.fullTitle}</h2>
             <p>{movie.year}</p>
             <p>{movie.imDbRating}</p>
           </div>
         ))}
       </div>
      ) : (
        <h2>No movies found! Try searching again</h2>
      )}
     
    </div>
  )
}
